### ISSUE TITLE
Feature request: --port flag

### ISSUE THREAD

**Issue by calebschoepp** [suborbital/e2core#32]
It would be handy if the port could be defined via flag in addition to the `ATMO_HTTP_PORT` env variable.

When I was deploying an application I wrote with Atmo to Heroku I had a lot of trouble with this. Heroku expects you to use an arbitrary port found in the env variable `PORT`. What I wanted to do was something like `atmo --port $PORT`. In the end I had to write a little bash script that exported the `PORT` variable to `ATMO_HTTP_PORT`.

**Comment by cohix** [comment]
@calebschoepp Agreed, would you like to take this on?

I'd say this can be generalized to read 'any env var options should also be available as flags'

**Comment by calebschoepp** [comment]
@cohix Yep, I'll take this on.

**Comment by calebschoepp** [comment]
@cohix quick update. This is still sitting on my todo list but I'm finding myself increasingly busy. Please feel free to pick up this task if you want it quicker than I can do it. I only ask that you assign yourself to the task so that I don't duplicate work if you do pick it up. Thanks :smile:

**Comment by cohix** [comment]
@calebschoepp sounds good!

**Comment by denopink** [comment]
@cohix can I take this on?

**Comment by denopink** [comment]
@cohix while I'm on this ticket, do you want me to take care of the other env vars as well?

https://github.com/suborbital/vektor/blob/6ac9d58ceaa6c3392031436094b74253fd34d8ad/vk/options.go#L13-L18

**Comment by cohix** [comment]
@denopink yes I think that makes sense!
